services:
  - type: web
    name: ara-rank-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: GITHUB_REPO
        value: allamrf865/ara-models
      - key: GITHUB_TOKEN
        sync: false
      - key: ARTIFACT_TAG
        value:
      - key: ARTIFACT_ZIP_URL
        value:
